exams/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'exams'


urlpatterns = [
path('index/', views.index, name='index'),
path('deo/', views.deoList.as_view(), name='deo'),
path('deo/<int:pk>', views.deoUpdate.as_view(), name='update'),
path('qc/<int:pk>', views.qcUpdate.as_view(), name='qc_update'),
path('qc/', views.qcList.as_view(), name='qc'),
#path('qc/<int:pk>', views.QuesDeleteView.as_view(), name='qcdelete'),
url(r'^qc/(?P<pk>\d+)/$', views.QuesDeleteView.as_view(), name='qcdelete'),

]

mega/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('exams.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exams/models.py
from django.db import models
from django.shortcuts import reverse
from django_extensions.db.fields import AutoSlugField
import pytesseract
from PIL import Image, ImageEnhance, ImageFilter


# Create your models here.
class Ques(models.Model):
    title=models.CharField(max_length=70)
    slug=AutoSlugField(populate_from='title', overwrite=True)
    img = models.ImageField(upload_to='images')
    text=models.TextField(max_length=250 ,blank=True)
    ocrtext=models.CharField(max_length=70,blank=True)
    post_date = models.DateField(auto_now_add=True)
    status = models.BooleanField(default=True, verbose_name="Approve")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('exams:update', args=[self.pk])

    def get_absolute_url_qc(self):
        return reverse('exams:qc_update', args=[self.pk])
    
    def save(self, *args, **kwargs):
        if self.img:
            im = Image.open(self.img)
            im = im.convert('L')                             # grayscale
            im = im.filter(ImageFilter.MedianFilter())       # a little blur
            im = im.point(lambda x: 0 if x < 140 else 255)
            self.ocrtext = pytesseract.image_to_string(im)
        super(Ques, self).save(*args, **kwargs)


    

exams/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView,DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from .models import Ques
from django.contrib import messages
from django.views.generic import ListView



# Create your views here.
def index(request):
    template = "exams/index.html"
    return render(request,template)

class deoList(ListView):
    model = Ques
    template_name='exams/deoList.html'
    context_object_name = 'ques'
    queryset = Ques.objects.filter(status=True)
    ordering=['-post_date']

class qcList(ListView):
    model = Ques
    template_name='exams/qcList.html'
    context_object_name = 'ques'
    queryset = Ques.objects.filter(status=True)
    ordering=['-post_date']

class deoUpdate(UpdateView):
    model = Ques
    fields = ['text',]
    success_url = '/deo'
    queryset = Ques.objects.filter(status=True)
    template_name= 'exams/update_form.html'

class qcUpdate(UpdateView):
    model = Ques
    fields = ['status',]
    success_url = '/qc'
    queryset = Ques.objects.filter(status=True)
    template_name= 'exams/qc_update_form.html'

class QuesDeleteView(DeleteView):
    model = Ques
    success_url = '/qc'
    success_message = "'%(name)s'  deleted..."

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        name = self.object.title
        request.session['name'] = name
        message = 'Entry: ' + request.session['name'] + ' deleted successfully'
        messages.success(self.request, message)
        return super(QuesDeleteView, self).delete(request, *args, **kwargs)

def approve_group(request, pk):
    ques = Ques.objects.get(pk=pk)
    ques.status = False
    ques.save()
    return redirect(request, 'approved')


    



    

exams/templates/exams/deoList.html
{% extends "exams/index.html" %}
{% block main %}
<div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Start Data Entry</h1>
          <table class="table table-hover">
              <tr>
                  
                  <th>title</th>
                  <th>image</th>
                  <th>action</th>
                </tr>
                <tr>
                    {% for q in ques %}
                    <th>{{ q.title }}</th>
                    <th>
                            
                        <img src="{{ q.img.url }}"  class="img-square" width="400" height="200" alt="{{ q.title }}">
                    </th>
                    <th>
                        <a href="{{ q.get_absolute_url }}" class="btn btn-success">ADD</a>
                    </th>
                    
                </tr>
                {% endfor %}       
                
              
              
            </table>
              
              </div>
      </div>

{% endblock %}

exams/templates/exams/index.html
{% load static %}
<html>
    <head>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/js/bootstrap.min.js" integrity="sha384-7aThvCh9TypR7fIc2HV4O/nFMVCBwyIUKL8XCtKE+8xgCgl/PQGuFsvShjr74PBp" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
    </head>
    <body>
        <div class="jumbotron">
            <center>
            <h1 class="display-4">Welcome</h1>

                <a class="btn btn-primary btn-lg" href="{% url "exams:deo" %}" role="button">Data Entry Operator</a>
                <a class="btn btn-primary btn-lg" href="{% url "exams:qc" %}" role="button">Quality Checking</a>
            </center>

            </p>
          </div>
          {% block main %}
          {% endblock %}
    </body>
</html>

exams/templates/exams/qcList.html
{% extends "exams/index.html" %}
{% block main %}
<div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Qc Control</h1>
          <table class="table table-hover">
              <tr>
                  
                  <th>title</th>
                  <th>image</th>
                  <th>ocrtext</th>
                  <th>text</th>
                  <th>action</th>
                </tr>
                {% for q in ques %}
                <tr class={{ q.pk }}>
                    <th>{{ q.title }}</th>
                    <th>
                            
                        <img src="{{ q.img.url }}"  class="img-square" width="400" height="200" alt="{{ q.title }}">
                    </th>
                    <th>{{ q.ocrtext }}</th>
                    <th>{{ q.text }}</th>
                    <th>
                            <a href="{{ q.get_absolute_url_qc }}" class="btn btn-success">ADD</a>

                            <form action="{% url 'exams:qcdelete' pk=q.pk %}" method="POST">
                                    {% csrf_token %}
                                        <input class="btn btn-default btn-danger" type="submit" value="Delete"/>
                                </form>                    </th>
                    
                </tr>
                {% endfor %}       
                
              
              
            </table>
              
              </div>
      </div>

{% endblock %}

exams/templates/exams/qc_update_form.html
{% extends "exams/index.html" %}
{% block main %}
<div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Verify Data Entry</h1>
        
         
          <form method="post">{% csrf_token %}
              <img src="{{ object.img.url }}" alt="{{ object.img.url }}" width="400" height="200">
                
              <br>
              <br>
              {{ form.as_p }}
              <input type="submit" value="Submit">
          </form>
         
                   
       
              </div>
      </div>
     
            
            

{% endblock %}

exams/templates/exams/ques_confirm_delete.html
{% extends "exams/index.html" %}
{% block main %}
<div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Delete  Entry</h1>
        
         
          <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input type="submit" value="Confirm">
        </form>
                   
              
              </div>
      </div>

{% endblock %}

exams/templates/exams/update_form _qc.html
{% extends "exams/index.html" %}
{% block main %}
<div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Enter Data Entry</h1>
        
         
          <form method="post">{% csrf_token %}
              
            <img src="{{ object.img.url }}" alt="{{ object.img.url }}" width="400" height="200">
            Enter Data:<p>{{ object.text }}</p>
            Generated OCR:<p>{{ object.ocrtext }}</p>

              {{ form.as_p }}
              <input type="submit" value="Submit">
          </form>
                   
              
              </div>
      </div>

{% endblock %}

exams/templates/exams/update_form.html
{% extends "exams/index.html" %}
{% block main %}
<div class="jumbotron jumbotron-fluid">
        <div class="container">
          <h1 class="display-4">Enter Data Entry</h1>
        
         
          <form method="post">{% csrf_token %}
              <img src="{{ object.img.url }}" alt="{{ object.img.url }}" width="400" height="200">
                
              <br>
              <br>
              {{ form.as_p }}
              <input type="submit" value="Submit">
          </form>
         
                   
          <div id="preview_div"></div>
              </div>
      </div>
      <script>
            $(document).ready(function(){
              $("#id_text").keyup(function(event){ 
                $("#preview_div").html($("#id_text").val());
              }
            );
            }
            );
            </script>
            
            

{% endblock %}